# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_box = "ubuntu/jammy64"
vm_box_version = "20230314.0.0"
#vm_hostname = "vagrant-ubuntu-#{ubuntu_codenames[ubuntu_release]}"
vm_hostname = "client.aux250"
vm_name = "client"
vm_size = {"cpus" => 4, "memory" => 6144}

Vagrant.configure("2") do |config|

  config.vm.box              = vm_box
  config.vm.box_version      = vm_box_version
  config.vm.box_check_update = false
  config.vm.boot_timeout     = 600

  config.vm.hostname = vm_hostname

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = vm_size["cpus"]
    vb.gui    = false
    vb.memory = vm_size["memory"]
    vb.name   = vm_name
    # Avoid errors with the two following
    vb.check_guest_additions = false
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    # No need for audio in a server-type VM...
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  # Perform base-system customizations and install project-specific dependencies...
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /home/vagrant/.ssh
    echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBrZKr9CiUatRAOBWQt11FBNVAZG5kJaQgv2ay53+AWA will@laptop" >> /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    sudo add-apt-repository ppa:ansible/ansible -y
    sudo apt-get update -y -qq
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ansible
    ip -4 a|grep inet
  SHELL
#  config.vm.provision "shell", path: "../vagrant/provision.sh",
#                               env: {"HOST_TIMEZONE" => Time.now.zone},
#                               privileged: false,  # ...run as the "vagrant" user.
#                               binary: true  # ...don't convert to CRLF on Windows.

  config.vm.provision "ansible_local" do |ansible|
    #ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.raw_arguments = ["-e ip_address_host=10.23.105.46 -e ansible_user=vagrant"]
  end

  # If needed, we prefer to share inside user's home directory
  config.vm.synced_folder "./", "/vagrant", disabled: false
  # Make the current directory visible (and editable) inside the VM...
  config.vm.synced_folder ".", "/home/vagrant/k8s-app", create: true, SharedFoldersEnableSymlinksCreate: false
end
